### PR TITLE
Added Expo

### PR DESCRIPTION
**Pull request by kirakik**

### CODE REVIEW

**Comment by bnb** [comment]
Currently the Expo org doesn't actually have any Good First Issues 😟

I've [reached out](https://twitter.com/bitandbang/status/1069379054787354624) to them on Twitter, hopefully they respond soon here!

**Comment by bnb** [comment]
The project has added good first issue labels 🎊

**Comment by maddhruv** [comment]
@bnb expo still doesn't have any good-first-issue
image

**Comment by bnb** [comment]
Currently no good first issues. Going to close this for now, but please feel free to re-open if they eventually have issues labeled good-first-issue!

**Pull request closed without merging**
