### PR TITLE
Added docz

### PR DESCRIPTION
**Pull request by kirakik**

### CODE REVIEW

**Comment by bnb** [comment]
Unfortunately it looks like Docz doesn't have open issues labeled "Good First Issue", haven't historically used the label (there is 1 issue of ~400 labeled with it that's closed).

I'll leave this open for a bit and reach out privately to the maintainer, but it looks like it's primarily one maintainer and I'd prefer not to publicly reach out to them and increase the burden of maintenance ❤️

**Comment by pedronauck** [comment]
Hi @bnb, I added some issues with #goodfirstissue label now, thanks to the advice 🙏

**Comment by maddhruv** [comment]
@kirakik please update the README as well and resolve the conflicts
Thanks for the PR :smile:

**Comment by kirakik** [comment]
Done @maddhruv

**Pull request merged**
