### PR TITLE
Search tests

### PR DESCRIPTION
**Pull request by kennethvandenberghe**
Added a first attempt for testing search.js

### CODE REVIEW

**Comment by bnb** [comment]
This is awesome, thanks a ton for the contribution! Will review shortly 🤗

**Comment by maddhruv** [comment]
image
@kennethvandenberghe thanks for making this PR
please rebase and resolve these issues
will merge :raised_hands:

**Comment by kennethvandenberghe** [comment]
I resolved the conflicts.

**Comment by maddhruv** [comment]
thanks, @kennethvandenberghe for this wonderful work
wish to see more from you

**Pull request merged**
