### PR TITLE
prompt -[sort, name - id]

### PR DESCRIPTION
**Pull request by maddhruv**
image

### CODE REVIEW

**Comment by bnb** [comment]
Looks good to me. Do we want to add a "description" property to `projects.js`? I just realized we 100% lost that context when we removed the `command` functionality and started using `action`.

**Comment by maddhruv** [comment]
I don't think a description is required as such
people coming to find good-first-issues might already know about the project (90%+) times

Also, in my opinion, even if we add the description field, it would  only _increase_ one entity for a new contribution(project addition)
so -1 from me :|

**Comment by bnb** [comment]
That's fine for this PR. I disagree that people would already know projects – I certainly wouldn't know what wolkenkit or gutenberg were if I weren't working on this project.

Think of organizers at a meetup using Good First Issue as a way to help introduce people to contributing to open-source. Giving people descriptions allows them to choose which project to contribute to.

**Comment by maddhruv** [comment]
Merging will follow up the discussions in #25

**Comment by maddhruv** [comment]
The commit had a bug
I missed it :cry: 
while doing `good-first-issue`
it takes the prompt choice string as input and then responded with a not found
image


! Will try to catch this up later

**Pull request merged**
