### PR TITLE
fixes #46

### LINKED ISSUE #46: Cannot find module '../data/projects.json'
Source: https://twitter.com/jeremenichelli/status/1065261579271315456?s=20

### PR DESCRIPTION
**Pull request by maddhruv**
please don't merge unless flag

### CODE REVIEW

**Comment by maddhruv** [comment]
:green_apple: works for both my machines

**Comment by bnb** [comment]
Getting this error using Node.js v10:
image

**Comment by bnb** [comment]
That module is being included by Jest: 
image

**Comment by bnb** [comment]
Okay going to merge + ship and see if that issue persists on v10 when installing globally.

**Pull request merged**
