### PR TITLE
Add React & React Native

### PR DESCRIPTION
**Pull request by kirakik**
Should I open a different PR for each?

### CODE REVIEW

**Comment by maddhruv** [comment]
Can merge and publish 0.19.0 :+1:

**Comment by kirakik** [comment]
@maddhruv Could you let me know in which order you're planning on merging the PRs? Each time one in merged new conflicts arise in the others. It'd be easier to resolve the conflicts in the next one as they're merged and not all of them each time

**Comment by maddhruv** [comment]
actually we are following an order for releases - every project addition is a feature and hence releasing a minor version with each project addition

**Comment by kirakik** [comment]
That's what I understood initially, but then #70 (tagged with 0.21.0) was merged before this PR (tagged with 0.19.0). Also, I noticed 0.19.0 was already released, but doesn't include this PR, which is why I'm a little confused

**Comment by maddhruv** [comment]
maybe there's a little confusion with the milestone taggings
will reach you back
/cc @bnb

**Comment by maddhruv** [comment]
@kirakik actually 0.19.0 and 0.18.0 landed together
and hence this PR fall back
adding this to a later release
would it work?

**Pull request merged**
